Задание 1

Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [35]:
import pandas as pd
import re

In [26]:

ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')
avg_rating = ratings[['movieId', 'rating']].groupby('movieId').mean().reset_index()
merge = movies.merge(avg_rating, on='movieId', how='left')
def filter_(m):
    if 2 >= float(m):
        return 'низкий рейтинг'
    elif 4.5 >= float(m):
        return 'средний рейтинг'
    elif 4.5 < float(m):
        return 'высокий рейтинг'
merge['class'] = merge['rating'].apply(filter_)
merge.sample(30)

,movieId,title,genres,rating,class
4594,6832,Regarding Henry (1991),Drama,3.600000,средний рейтинг
8163,102666,Ivan Vasilievich: Back to the Future (Ivan Vas...,Adventure|Comedy,4.500000,средний рейтинг
3243,4384,Lumumba (2000),Drama,3.000000,средний рейтинг
8999,139855,Anomalisa (2015),Animation|Comedy|Fantasy,3.250000,средний рейтинг
4906,7354,Mad Dog and Glory (1993),Comedy|Drama|Romance,3.333333,средний рейтинг
2273,3016,Creepshow (1982),Horror,3.071429,средний рейтинг
3176,4278,Triumph of the Will (Triumph des Willens) (1934),Documentary,4.166667,средний рейтинг
3146,4233,Tomcats (2001),Comedy,2.000000,низкий рейтинг
6089,42004,Transamerica (2005),Adventure|Comedy|Drama,3.500000,средний рейтинг
8465,112515,"Babadook, The (2014)",Drama|Horror|Thriller,4.500000,средний рейтинг
7502,83270,Made in Dagenham (2010),Comedy|Drama,2.000000,низкий рейтинг
7356,78544,Ricky Gervais Live 3: Fame (2007),Comedy,3.000000,средний рейтинг
1262,1677,Critical Care (1997),Comedy|Drama,2.000000,низкий рейтинг
7709,90245,Antonio Gaudí (1985),Documentary,4.000000,средний рейтинг
8602,117881,Still Alice (2014),Drama,3.800000,средний рейтинг
4773,7104,1941 (1979),Comedy|War,2.666667,средний рейтинг
229,266,Legends of the Fall (1994),Drama|Romance|War|Western,3.397059,средний рейтинг
935,1235,Harold and Maude (1971),Comedy|Drama|Romance,4.288462,средний рейтинг
1193,1590,Event Horizon (1997),Horror|Sci-Fi|Thriller,2.940000,средний рейтинг
2668,3571,Time Code (2000),Comedy|Drama,3.000000,средний рейтинг
8005,97304,Argo (2012),Drama|Thriller,3.982143,средний рейтинг
4322,6315,Wildcats (1986),Comedy,1.833333,низкий рейтинг
8490,113348,Teenage Mutant Ninja Turtles (2014),Action|Adventure|Comedy,2.750000,средний рейтинг
2540,3401,Baby... Secret of the Lost Legend (1985),Adventure|Sci-Fi,2.200000,средний рейтинг
471,538,Six Degrees of Separation (1993),Drama,3.583333,средний рейтинг
2789,3730,"Conversation, The (1974)",Drama|Mystery,4.205882,средний рейтинг
4730,7052,Mary of Scotland (1936),Drama,3.000000,средний рейтинг
8918,135777,Golmaal (2006),Children|Comedy,4.500000,средний рейтинг
7844,93502,"Ledge, The (2011)",Drama|Thriller,2.500000,средний рейтинг
2425,3225,Down to You (2000),Comedy|Romance,2.000000,низкий рейтинг

Задание 2

Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

Результат классификации запишите в отдельный столбец region.

In [38]:
keywords = pd.read_csv('keywords.csv')
keywords.sample(30)
geo_data = {'Центр': ['москва', 'тула', 'ярославль'],'Северо-Запад': ['петербург', 'псков', 'мурманск'],'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск'] }
def location(word):
    for key in geo_data.keys():
        for city in geo_data[key]:
            if re.search(city, word, re.I):
                return key
    return 'undefined'
keywords['region'] = keywords['keyword'].apply(location)
keywords.sample(30)

                                                 keyword   shows        region
4467                                     adobe photoshop   54052     undefined
40315                                            электро    8335     undefined
90702                    канал россия 1 официальный сайт    4182     undefined
60974                                     трахнул пьяную    5939     undefined
47293                                     акции газпрома    7219     undefined
52824  библио глобус туроператор санкт петербург офиц...    6470  Северо-Запад
45463                                 хочу работу ижевск    7563     undefined
88050                                   скачать кризис 2    4533     undefined
39037                              сибэко личный кабинет    8632     undefined
73281                                    сын уилла смита    4736     undefined
77478                                             ххх ок    4766     undefined
69900              бегония уход в домашних условиях фото    5085     undefined
39119                               актовегин инструкция    8635     undefined
46859                                                впч    7276     undefined
85315                                           ru board    4257     undefined
404                                        корреспондент  398029     undefined
41300                                   евгений плющенко   10474     undefined
18175                                        синяя птица   16685     undefined
87876                                        smarty sale    4135     undefined
81057                                шант тв прямой эфир    4831     undefined
31596                             интернет магазин обуви   10745     undefined
70856                                     бумер не плачь    6124     undefined
54840                                   сервировка стола    6314     undefined
84942                   сколько калорий в куриной грудке    4379     undefined
30244                                         интересное   10758     undefined
17580                                                фак   17184     undefined
99129                            перелом смотреть онлайн    3924     undefined
11575             математика 3 класс моро 1 часть ответы   24985     undefined
67744                                 знакомство майл ру    5989     undefined
1837                                               нн ру  111033     undefined

Задание 3 (бонусное)

Есть мнение, что “раньше снимали настоящее кино, не то что сейчас”. Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

В переменную years запишите список из всех годов с 1950 по 2010.

Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:

для каждой строки пройдите по всем годам списка years
если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год
Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’

Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга

In [71]:
years = list(range(1950,2011))
ratings = pd.read_csv('ratings.csv')
avg_rating = ratings[['movieId', 'rating']].groupby('movieId').mean().reset_index()
movies = pd.read_csv('movies.csv')[['movieId', 'title']].merge(avg_rating, on='movieId', how='left')
def production_year(name):
    for year_number in years:
        if re.search(str(year_number), name):
            return str(year_number)
    return 1900
movies['year'] = movies['title'].apply(production_year)
avg_year = movies[['year','rating']].groupby('year').mean().reset_index()
avg_year.head()

   year    rating
0  1900  3.271038
1  1950  3.501464
2  1951  3.718044
3  1952  3.700104
4  1953  3.586757